apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet.dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: dotnet
    repoURL: butloo.azurecr.io
    targetRevision: 0.{__tag__}.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true